lawyersys/cases/urls.py
from django.urls import path
from cases import views
 


app_name = 'cases'

urlpatterns = [
    path('', views.index, name='index'),       
 
]

lawyersys/lawyersys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from cases import views

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('', include('cases.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lawyersys/cases/models.py
from django.db import models

# Create your models here.

lawyersys/cases/views.py
from django.shortcuts import render

# Create your views here.


def index(request):      
    context = {                   
                 
              }
    return render(request, 'index.html', context)




lawyersys/cases/templates/includes/base.html
{% load static %}
<!DOCTYPE html>
 
<html lang="ar" dir="rtl">    
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    </head>
    <body>       

        {% include "includes/header.html" %}
        {% block content %}

        {% endblock %}
        {% include "includes/footer.html" %}

        <script type="text/javascript" src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    </body>
</html>

lawyersys/cases/templates/includes/footer.html

<div class="container-fluid">
    
    <footer class="text-center text-lg-start text-white" style="background-color: #2B2B2B">
        <!-- Section: Social media -->
        <section
               class="d-flex justify-content-between p-4"
               style="background-color: #626667"
               >
        <!-- Left -->
        <div class="me-5">
          <span class="footer_txt">تواصل معنا على وسائل التواصل الاجتماعي:</span>
        </div>
        <!-- Left -->
  
        <!-- Right -->
        <div >
          <a href="" class=" me-4" style="color:#DB9437">
            <i class="fab fa-facebook-f"></i>
          </a>
          <a href="" class="  me-4" style="color:#DB9437">
            <i class="fab fa-twitter"></i>
          </a>
          <a href="" class="  me-4" style="color:#DB9437">
            <i class="fab fa-google"></i>
          </a>
          <a href="" class="  me-4" style="color:#DB9437">
            <i class="fab fa-instagram"></i>
          </a>
          <a href="" class="  me-4" style="color:#DB9437">
            <i class="fab fa-linkedin"></i>
          </a>
          <a href="" class="  me-4" style="color:#DB9437">
            <i class="fab fa-github"></i>
          </a>
        </div>
        <!-- Right -->
      </section>
        <div
           class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
              <p style="color:#DB9437">Copyright ©2024 Jaber Lawyers. All Rights Reserved </p>

         
      </div>
     </footer>         
</div>    

lawyersys/cases/templates/includes/header.html
<nav class="navbar navbar-expand-lg  navbar-dark  fixed-top" style="background-color: #444444;font-family:GE Dinkum;font-size:22px;">
    <div class="container-fluid">
        <!-- Brand/logo -->
        
        <a class="navbar-brand" href="#"  style="font-family:GE Dinkum;font-size:25px;font-weight: bold;color:#DB9437;">مجمع جبر لاعمال المحاماة</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav se-auto mb-2 mb-lg-0" >
          <li class="nav-item">
           
            <a class="nav-link active" aria-current="page" href="{% url 'cases:index' %}" style="font-family:GE Dinkum;font-size:22px;color:#DB9437;">الشاشة الرئيسة</a>
            
          </li>
  
         

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color:#DB9437;">
                   من نحن
            </a>
            <ul class="dropdown-menu"  style="text-align:right;">
              <li><a class="dropdown-item jaber_txt" href="#">فريق العمل</a></li>             
             
              
              
            </ul>
          </li>

          <li class="nav-item">
            <a class="nav-link jaber_txt" aria-current="page" href="#" style="font-family:GE Dinkum;font-size:22px;color:#DB9437;">خدماتنا</a>
          </li>
  
          
           
               
          
  
  
          
         
         
  
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color:#DB9437;">
                   الاستشارات
            </a>
            <ul class="dropdown-menu"  style="text-align:right;">
              <li><a class="dropdown-item jaber_txt" href="#">احجز لاستشارة مدفوعة</a></li>             
              <li><a class="dropdown-item jaber_txt" href="#">ارسل لاستشارة مجانية</a></li>
              
              
            </ul>
          </li>


  
             <li class="nav-item">
                 <a class="nav-link jaber_txt" aria-current="page" href="#" style="font-family:GE Dinkum;font-size:22px;color:#DB9437;">انظمة وقوانين</a>
             </li>

             <li class="nav-item">
                <a class="nav-link jaber_txt" aria-current="page" href="#" style="font-family:GE Dinkum;font-size:22px;color:white;">مرحبا يالزائر</a>
            </li> 

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color:#DB9437;">
                   دخول 
            </a>
            <ul class="dropdown-menu"  style="text-align:right;">
              <li><a class="dropdown-item jaber_txt" href="#">دخول للنظام</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item jaber_txt" href="#">تسجبل جديد</a></li>
              
              
            </ul>
          </li>

          <li class="nav-item">
            <a class="nav-link jaber_txt" aria-current="page" href="#" style="font-family:GE Dinkum;font-size:22px;color:#DB9437;">en</a>
          </li>
          
  
        </ul>
  
        <form class="d-flex" role="search" >
          <input class="form-control me-2" type="search" placeholder="ابحث عن" aria-label="Search" style="color:#DB9437;">
          <button class="btn btn-outline-success" type="submit">البحث</button>
        </form>
      </div>
    </div>
  </nav>

lawyersys/cases/templates/index.html
{% extends 'includes/base.html' %}


{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static 'css/clients.css' %}">
  {% comment %} --------------------------- {% endcomment %}
          <br> <br> <br>




  <div class="container-fluid ">
 
 
   
          <div class="row p-3 bg-light">
                <div class="container-fluid">

   <div class="row p-3 bg-light">


<!-- Main content -->
<section class="content">
      <div class="container-fluid">
        
            <div class="image" style="text-align:center">
                  {% load static %}
                 <img class="doc_image" src="{% static 'dist/img/about.jpeg' %}"  style="width:650px;">
            </div>

            <hr>
            <div class="row p-2 bg-light">
                  <p  class="head_txt ">خدماتنا</p>
               <hr>

       <!-- Small boxes (Stat box) -->
       <div class="row">
            <div class="col-lg-2 col-6">
              <!-- small box -->
              <div class="small-box bg-dark">
                <div class="inner">
                  <h3 > </h3>
  
                  <h4 class="dash_board" style="color:#DB9437;font-size:22px">استشارات ودراسات</h4>
                </div>
                <div class="icon">
                  <i class="fas  fa-user"></i>
                </div>
                <a href="#" class="small-box-footer"><span style="color:#DB9437">التفاصيل</span> <i class="fas fa-arrow-circle-right"></i></a>
              </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-2 col-6">
              <!-- small box -->
              <div class="small-box bg-dark">
                <div class="inner">
                  <h3> <sup style="font-size: 20px"> </sup></h3>
  
                 <h4 class="dash_board" style="color:#DB9437;font-size:22px">تنفيذ احكام</h4>
                </div>
                <div class="icon">
                  <i class=" fas fa-gavel"></i>
                </div>
                <a href="#" class="small-box-footer"><span style="color:#DB9437">التفاصيل</span> <i class="fas fa-arrow-circle-right"></i></a>
              </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-2 col-6">
              <!-- small box -->
              <div class="small-box bg-dark ">
                <div class="inner">
                  <h3> </h3>
  
  
                    <h5 class="dash_board" style="color:#DB9437;font-size:22px">مرافعات</h5>
                </div>
                <div class="icon">
                  <i class="fas fa-gavel"></i>
                </div>
                <a href="#" class="small-box-footer"><span style="color:#DB9437">التفاصيل</span> <i class="fas fa-arrow-circle-right"></i></a>
              </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-2 col-6">
              <!-- small box -->
              <div class="small-box bg-dark">
                <div class="inner">
                  <h3> </h3>
  
  
                    <h5 class="dash_board" style="color:#DB9437;font-size:22px">عقود واتفاقيات</h5>
                </div>
                <div class="icon">
                  <i class="fas fa-file"></i>
                </div>
                <a href="#" class="small-box-footer"><span style="color:#DB9437">التفاصيل</span> <i class="fas fa-arrow-circle-right"></i></a>
              </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-2 col-6">
              <!-- small box -->
              <div class="small-box bg-dark " >
                <div class="inner">
                  <h3> </h3>
  
  
                    <h5 class="dash_board" style="color:#DB9437;font-size:22px">شركات واستثمارات</h5>
                </div>
                <div class="icon">
                  <i class="fas fa-building"></i>
                </div>
                <a href="#" class="small-box-footer"><span style="color:#DB9437">التفاصيل</span> <i class="fas fa-arrow-circle-right"></i></a>
              </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-2 col-6">
              <!-- small box -->
              <div class="small-box bg-dark">
                <div class="inner">
                  <h3> </h3>
  
                    <h5 class="dash_board" style="color:#DB9437;font-size:22px">صلح وتحكيم</h5>
                </div>
                <div class="icon">
                  <i class="fas fa-folder-open"></i>
                </div>
                <a href="#" class="small-box-footer" ><span style="color:#DB9437">التفاصيل</span> <i class="fas fa-arrow-circle-right"></i></a>
              </div>
            </div>
            <!-- ./col -->
  
              <hr>
  

              

            <div class="container pe-5 ps-5">
                  
            </div>      

            <div class="row p-2 bg-light">
                  <p  class="head_txt ">عملائنا</p>
               <hr>
            

               {% load static %}               
                
             <style>
                  .doc_image {
                        
                              border: 1px solid #ddd;
                              border-radius: 4px;
                              padding: 5px;
                              width: 150px;
                               
                              background-color: white;
                              box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
                        }
                  .doc_image:hover {
                              box-shadow: 0 0 2px 1px rgba(0, 140, 186, 0.5);
                            }
                  
             </style>       
             <div class="container" style="text-align:center">
                  <img class="doc_image" src="{% static 'dist/img/companies/2.jpg' %}"  style="width:150px;">   
                  <img class="doc_image" src="{% static 'dist/img/companies/3.jpg' %}"  style="width:150px;">  
                  <img class="doc_image" src="{% static 'dist/img/companies/4.jpg' %}"  style="width:150px;">  
                  <img class="doc_image" src="{% static 'dist/img/companies/5.jpg' %}"  style="width:150px;">  
                  <img class="doc_image" src="{% static 'dist/img/companies/6.jpg' %}"  style="width:150px;">  
                   
                  <img class="doc_image" src="{% static 'dist/img/companies/7.jpg' %}"  style="width:150px;">  
                  <img class="doc_image" src="{% static 'dist/img/companies/8.jpg' %}"  style="width:150px;">
                  <img class="doc_image" src="{% static 'dist/img/companies/9.jpg' %}"  style="width:150px;">  
                  <img class="doc_image" src="{% static 'dist/img/companies/10.jpg' %}"  style="width:150px;">
                  <img class="doc_image" src="{% static 'dist/img/companies/11.jpg' %}"  style="width:150px;">
                  <br>
                  <img class="doc_image" src="{% static 'dist/img/companies/12.jpg' %}"  style="width:150px;">
                  <img class="doc_image" src="{% static 'dist/img/companies/13.jpg' %}"  style="width:150px;">
                  <img class="doc_image" src="{% static 'dist/img/companies/14.jpg' %}"  style="width:150px;">
                  <img class="doc_image" src="{% static 'dist/img/companies/15.jpg' %}"  style="width:150px;">
                  <img class="doc_image" src="{% static 'dist/img/companies/16.jpg' %}"  style="width:150px;">
                  
                  <img class="doc_image" src="{% static 'dist/img/companies/17.jpg' %}"  style="width:150px;">
                  <img class="doc_image" src="{% static 'dist/img/companies/18.jpg' %}"  style="width:150px;">
                  <img class="doc_image" src="{% static 'dist/img/companies/19.jpg' %}"  style="width:150px;">
                  <img class="doc_image" src="{% static 'dist/img/companies/20.jpg' %}"  style="width:150px;">
                  <img class="doc_image" src="{% static 'dist/img/companies/21.jpg' %}"  style="width:150px;">
             </div>

             <hr>
             <div class="row p-2 bg-light">
              <p  class="head_txt ">رؤيتنا</p>
           <hr>
           
           
           
           
         

           <div class="container" style="text-align:center">
                  <img class="doc_image" src="{% static 'dist/img/ourvision.png' %}"  style="width:750px;">   
                          
          </div>    
            

        </div>
      </div>
      </section>
  
  <!--   end column number 2      -->
     </div>
  <!--   end Row      -->

           
     

<br><br><br><br><br><br>
</div>

 


<br><br>

{% endblock %}

  {% block javascript %}
  {% endblock %}